# encoding: utf-8
# Author: LW


from xml.etree import ElementTree as ET
import time
import math
import dbmanager as hicis

xml_str = """<root>
<agentCode>M00000000047</agentCode>
				<businessNature>8</businessNature>
				<classCode>27</classCode>
				<startDate>2018-07-22T00:00:00</startDate>
				<endDate>2018-07-31T23:59:59</endDate>
				<operateDate>2018-07-03T12:23:59</operateDate>
				<orderId>180703122208176289</orderId>
				<planCode>P272017ZXTX000102</planCode>
				<policySort>0</policySort>
				<policyType>2</policyType>
				<riskCode>2711</riskCode>
				<sumAmount>44736700</sumAmount>
				<sumPremium>4292.00</sumPremium>
				<planFeeInfo>
					<currency>CNY</currency>
					<delinquentFee>4292.00</delinquentFee>
					<payNo>1</payNo>
					<payReason>R10</payReason>
					<planFee>4292.00</planFee>
					<serialNo>1</serialNo>
				</planFeeInfo>
				<sumQuantity>37</sumQuantity>
				<proposalAppliInfo>
					<identifyNumber>91500000MA5YTM6Y1R</identifyNumber>
					<identifyType>99</identifyType>
					<insuredName>重庆嵘之道体育文化传播有限公司</insuredName>
					<phoneNumber>13573228780</phoneNumber>
					<birthDate/>
					<postAddress/>
					<identifyDate>2030-01-01</identifyDate>
					<insuredNature>4</insuredNature>
					<insuredAddress/>
					<insuredIdentity/>
					<sex/>
					<mobile/>
					<email>phmmail@163.com</email>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
				</proposalAppliInfo>
				<proposalInsuredInfoList>
					<age>22</age>
					<birthDate>1995-12-03</birthDate>
					<identifyNumber>E58523118</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>王靖奇</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>0</serialNo>
					<sex>1</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>0</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>18</age>
					<birthDate>1999-08-29</birthDate>
					<identifyNumber>EB8897625</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>蒋哲岩</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>1</serialNo>
					<sex>1</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>1</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>22</age>
					<birthDate>1996-02-06</birthDate>
					<identifyNumber>E79938222</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>黄官勇</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>2</serialNo>
					<sex>1</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>2</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>25</age>
					<birthDate>1993-05-17</birthDate>
					<identifyNumber>EB8909264</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>王春顺</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>3</serialNo>
					<sex>1</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>3</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>19</age>
					<birthDate>1998-09-19</birthDate>
					<identifyNumber>EB8638453</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>谢沛含</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>4</serialNo>
					<sex>1</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>4</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>25</age>
					<birthDate>1993-07-06</birthDate>
					<identifyNumber>EB8928176</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>冉明阳</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>5</serialNo>
					<sex>1</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>5</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>19</age>
					<birthDate>1998-07-31</birthDate>
					<identifyNumber>EB8911372</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>刘锦泉</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>6</serialNo>
					<sex>1</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>6</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>24</age>
					<birthDate>1994-04-07</birthDate>
					<identifyNumber>E29311078</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>张亨</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>7</serialNo>
					<sex>1</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>7</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>21</age>
					<birthDate>1997-02-09</birthDate>
					<identifyNumber>E63835739</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>张港</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>8</serialNo>
					<sex>1</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>8</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>21</age>
					<birthDate>1997-02-28</birthDate>
					<identifyNumber>ED3422160</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>汤志勇</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>9</serialNo>
					<sex>1</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>9</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>23</age>
					<birthDate>1994-07-21</birthDate>
					<identifyNumber>EB8898600</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>张茂鑫</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>10</serialNo>
					<sex>1</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>10</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>18</age>
					<birthDate>1999-10-14</birthDate>
					<identifyNumber>EA5139336</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>李天月</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>11</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>11</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>18</age>
					<birthDate>1999-08-10</birthDate>
					<identifyNumber>EA9249269</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>王桢妮</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>12</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>12</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>19</age>
					<birthDate>1998-09-26</birthDate>
					<identifyNumber>EA7839471</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>刘远扬</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>13</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>13</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>21</age>
					<birthDate>1997-07-08</birthDate>
					<identifyNumber>EB8909257</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>卢宗其</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>14</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>14</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>23</age>
					<birthDate>1994-08-17</birthDate>
					<identifyNumber>E34436729</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>孙一心</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>15</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>15</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>24</age>
					<birthDate>1994-02-10</birthDate>
					<identifyNumber>ED3442586</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>冉晓芬</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>16</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>16</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>25</age>
					<birthDate>1993-01-29</birthDate>
					<identifyNumber>G46795397</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>王宇泽</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>17</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>17</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>22</age>
					<birthDate>1995-07-18</birthDate>
					<identifyNumber>EB8903036</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>向秋红</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>18</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>18</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>18</age>
					<birthDate>2000-01-05</birthDate>
					<identifyNumber>EB8911371</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>刘子怡</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>19</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>19</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>24</age>
					<birthDate>1994-03-28</birthDate>
					<identifyNumber>E24907275</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>罗依菲</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>20</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>20</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>23</age>
					<birthDate>1994-10-29</birthDate>
					<identifyNumber>EA5873692</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>连心瑀</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>21</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>21</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>24</age>
					<birthDate>1993-09-04</birthDate>
					<identifyNumber>EB2792386</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>冯芸艺</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>22</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>22</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>22</age>
					<birthDate>1996-02-06</birthDate>
					<identifyNumber>EB8898599</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>喻琴</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>23</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>23</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>25</age>
					<birthDate>1993-02-10</birthDate>
					<identifyNumber>E75519128</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>李莉</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>24</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>24</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>23</age>
					<birthDate>1994-08-28</birthDate>
					<identifyNumber>EB7833822</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>陈丽</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>25</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>25</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>21</age>
					<birthDate>1996-12-06</birthDate>
					<identifyNumber>EB8895942</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>周璐</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>26</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>26</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>25</age>
					<birthDate>1993-03-25</birthDate>
					<identifyNumber>EC1591578</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>范雨婷</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>27</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>27</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>23</age>
					<birthDate>1995-06-01</birthDate>
					<identifyNumber>EB8893048</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>杨霞</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>28</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>28</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>24</age>
					<birthDate>1993-08-20</birthDate>
					<identifyNumber>EB8906166</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>陈娟</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>29</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>29</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>21</age>
					<birthDate>1997-03-19</birthDate>
					<identifyNumber>EB8909256</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>邓攀</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>30</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>30</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>22</age>
					<birthDate>1996-05-22</birthDate>
					<identifyNumber>E99237940</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>胡金燕</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>31</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>31</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>38</age>
					<birthDate>1979-11-14</birthDate>
					<identifyNumber>PE1401727</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>黄诚胤</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>32</serialNo>
					<sex>1</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>32</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>55</age>
					<birthDate>1963-03-07</birthDate>
					<identifyNumber>PE0645357</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>许定国</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>33</serialNo>
					<sex>1</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>33</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>22</age>
					<birthDate>1995-12-17</birthDate>
					<identifyNumber>EB8905929</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>刘静怡</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>34</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>34</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>23</age>
					<birthDate>1994-12-02</birthDate>
					<identifyNumber>G42725164</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>汝秀花</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>35</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>35</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<proposalInsuredInfoList>
					<age>48</age>
					<birthDate>1970-06-13</birthDate>
					<identifyNumber>E03759860</identifyNumber>
					<identifyType>03</identifyType>
					<insuredFlag>1</insuredFlag>
					<insuredIdentity>99</insuredIdentity>
					<insuredName>吴群英</insuredName>
					<insuredNature>3</insuredNature>
					<phoneNumber/>
					<serialNo>36</serialNo>
					<sex>2</sex>
					<identifyDate>2030-01-01</identifyDate>
					<relateSerialNo>36</relateSerialNo>
					<mobile/>
					<email/>
					<postAddress/>
					<postCode/>
					<bank/>
					<account/>
					<linkerName/>
					<nationalityCode/>
					<benefitFlag/>
					<benefitRate>100</benefitRate>
					<occupationCode/>
					<insuredAddress/>
				</proposalInsuredInfoList>
				<requestInfo>
					<password>zxtx1709</password>
					<user>zhongxing</user>
					<transcationCode>ZXTX-xiandai20180713140341634075</transcationCode>
				</requestInfo>
				<riskInfoList>
					<amount>400000</amount>
					<kindCode>2711C01</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>200000</amount>
					<kindCode>2711F01</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>30000</amount>
					<kindCode>2711F02</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>2500</amount>
					<kindCode>2711F20</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>300000</amount>
					<kindCode>2711F03</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>150000</amount>
					<kindCode>2711F04</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>3000</amount>
					<kindCode>2711F17</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>10000</amount>
					<kindCode>2711F10</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>800</amount>
					<kindCode>2711F13</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>800</amount>
					<kindCode>2711F12</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>1000</amount>
					<kindCode>2711F06</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>2000</amount>
					<kindCode>2711F21</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>3000</amount>
					<kindCode>2711F22</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>3000</amount>
					<kindCode>2711F23</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>3000</amount>
					<kindCode>2711F07</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<riskInfoList>
					<amount>100000</amount>
					<kindCode>2711F11</kindCode>
					<premium>0</premium>
				</riskInfoList>
				<travelInfo>
					<destinationArea>韩国</destinationArea>
				</travelInfo>
				<productCode>P272017ZXTX0001</productCode>
</root>
"""

root =ET.XML(xml_str)

start_time = time.strptime(root.find('startDate').text, '%Y-%m-%dT%H:%M:%S')
end_time = time.strptime(root.find('endDate').text, '%Y-%m-%dT%H:%M:%S')
risk_code = root.find('riskCode').text
plan_code = root.find('planCode').text
product_code = plan_code[:-2]
order_id = root.find('orderId').text
agent_code = root.find('agentCode').text
sum_amount = float(root.find('sumAmount').text)
sum_premium = float(root.find('sumPremium').text)
apply_info_root = root.find('proposalAppliInfo')
insured_list = root.findall('proposalInsuredInfoList')
insured_cnt = len(insured_list)


chk_product_code = ''
chk_product_name = ''
chk_plan_code = ''
chk_plan_name = ''
chk_plan_sum_amount = 0.0

days = math.floor((time.mktime(end_time) - time.mktime(start_time)) / (60 * 60 * 24)) + 1

print("开始检查xml报文内容:")

sql = """select b.PRODUCTCODE,b.PRODUCTNAME,a.PROGRAMMECODE,a.PROGRAMMENAME,a.SUMAMOUNT 
from PRPDPROGRAMME a,PRPDPRODUCT b 
where a.PROGRAMMECODE='{0}'
and a.PRODUCTCODE = b.PRODUCTCODE""".format(plan_code)

row = hicis.find_one(sql)


print("3.保费检查：输入：", sum_premium)
chk_sum_premium = 0.0
insured_idx = 1
for insured in insured_list:
    sql = """select SUM(PREMIUM) from prpdratedate
where PLANCODE='{0}'
and TERMMINVALUE <= {1} AND TERMMAXVALUE >={1}
and AGEMINVALUE <= {2} AND AGEMAXVALUE>={2}
    """.format('27110024',  days,int(insured.find('age').text))
    row = hicis.find_one(sql)
    chk_sum_premium += row[0]
    print('\t\t {3:3d} 姓名：{0:5s} 年龄：{1:^3d} 保费：{2}  天数:{4}'.format(insured.find('insuredName').text, int(insured.find('age').text),row[0],insured_idx,days))
    insured_idx +=1
if round(chk_sum_premium,2) == sum_premium :
    print('\tV 检查结果：', '符合', sum_premium)
else:
    print('\tX 检查结果：', '不符合','合计人数：',insured_cnt, ' 输入：',sum_premium,'方案：',round(chk_sum_premium,2))



# sql = 'SELECT * FROM prpcmain where rownum<10'
# row = hicis.find_one(sql)

# print(row)
